# Docker Android APK 构建服务配置

services:
  # Android APK 构建服务
  android-builder:
    build:
      context: .
      dockerfile: Dockerfile.android
    image: drawsomething-android-builder:latest
    container_name: drawsomething-apk-builder
    volumes:
      # 挂载输出目录,用于导出 APK
      - ./output:/output
      # 挂载源代码(开发模式)
      - ./frontend/src:/app/frontend/src:ro
      - ./frontend/public:/app/frontend/public:ro
    environment:
      - BUILD_TYPE=debug
    # 构建完成后自动退出
    restart: "no"
    command: ["build-apk.sh", "debug"]

  # Release APK 构建服务
  android-builder-release:
    build:
      context: .
      dockerfile: Dockerfile.android
    image: drawsomething-android-builder:latest
    container_name: drawsomething-apk-builder-release
    volumes:
      - ./output:/output
      - ./frontend/src:/app/frontend/src:ro
      - ./frontend/public:/app/frontend/public:ro
    environment:
      - BUILD_TYPE=release
    restart: "no"
    command: ["build-apk.sh", "release"]
