"""add calls_remaining to users table

Revision ID: 4177e5bb3c85
Revises: 2583b75a606c
Create Date: 2025-10-29 01:34:49.986065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4177e5bb3c85'
down_revision: Union[str, Sequence[str], None] = '2583b75a606c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calls_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calls_remaining')
    # ### end Alembic commands ###
